---
title: "About"
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/nickpolimeni/
    - icon: github
      text: Github
      href: https://github.com/Nicholas-Polimeni
---

I'm a Computer Science student and Data Researcher at Georgia Tech's Urban Research Group, using software, GIS, and data science to highlight the impacts of policy decisions. My work includes developing a fuzzy entity resolution algorithm for parcel ownership analysis and uncovering factors influencing homeownership rates in Atlanta neighborhoods. This research helped identify $101M in lost revenue for Fulton County.

At Collins Aerospace, as a Software Engineer - AI/ML Data Platform, I led enhancements to Smartbid, an image processing and OCR data pipeline for mechanical part information extraction.

My passion lies in leveraging technology and public policy for a sustainable, equitable world. As an environmental advocate with Citizens' Climate Lobby, I've lobbied for climate policies and previously led the Georgia Tech chapter, gaining support from local leaders.

::: {.callout-note}
Open to Full-Time Software and Data Roles Starting May 2024.
:::

::: {.callout-note}
This website is new. To see my previous website, click [here](old/v1/index.html).
:::